# Generated by Django 4.2.5 on 2023-09-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0002_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='date_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
